// This file list is case sensitive

// This list can be regenerated by running the following:
// AsosCodingStyle.JsUnitTests>dir /s /p /b specs\*.specs.js
// and then stripping out the JsUnitTests directory and replacing \ with /
var specFiles = [
    '/specs/app/app.specs.js',
    '/specs/app/app2.specs.js'
];