//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsosCodingStyle.Data {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AsosCodingStyle.Data.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;ProductId&quot;:1,&quot;Description&quot;:&quot;Larkee 8Xr Straight Fit Jeans&quot;,&quot;Size&quot;:&quot;Large&quot;,&quot;Colour&quot;:&quot;Blue&quot;,&quot;ImageUrl&quot;:&quot;http://www.houseoffraser.co.uk/Diesel+Larkee+8Xr+Straight+Fit+Jeans/128168417,default,pd.html&quot;},{&quot;ProductId&quot;:2,&quot;Description&quot;:&quot;Larkee 8Z8 Straight Leg Jeans&quot;,&quot;Size&quot;:&quot;Large&quot;,&quot;Colour&quot;:&quot;Blue&quot;,&quot;ImageUrl&quot;:&quot;http://www.houseoffraser.co.uk/Diesel+Larkee+8Z8+Straight+Leg+Jeans/171615659,default,pd.html&quot;},{&quot;ProductId&quot;:3,&quot;Description&quot;:&quot;Zatiny 8XR Bootcut Jeans&quot;,&quot;Size&quot;:&quot;Large&quot;,&quot;Colour&quot;:&quot;Blue&quot;,&quot;ImageUrl&quot;:&quot;http://www.h [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
    }
}
